---
title: "The Economic Incidence of Wildfire Suppression in the United States"
type: "article"
author: ["Patrick Baylis", "Judson Boomhower"]
year: "2023"
publication: "American Economic Journal: Applied"
preprint: "https://www.nber.org/papers/w26550.pdf"
doi: "https://doi.org/10.1257/app.20200662"
# materials: "https://www.aeaweb.org/articles?id=10.1257/app.20200662"
toc: false
categories:
  - patrick
  - fires
  - journal article
---

## Citation

> Baylis, Patrick, and Judson Boomhower. "The economic incidence of wildfire suppression in the United States." American Economic Journal: Applied Economics 15, no. 1 (2023): 442-473.

## Abstract

This study measures the degree to which public expenditures on wildfire protection subsidize development in harm's way. We use administrative data on firefighting expenditures to measure the causal effect of nearby homes on the amount spent to extinguish wildfires. We use these estimates in an actuarial calculation yielding geographically differentiated expected implicit subsidies for homes across the western United States. The expected net present value of this subsidy can exceed 20 percent of home value, increases with fire hazard, and decreases surprisingly steeply with development density. We discuss potential behavioral responses by individuals and local governments using a simple economic model.